### ISSUE TITLE
Measure list: No results found

### ISSUE THREAD

**Issue by dagpunk** [kabir-rab/master-items-viewer-lite#1]
Hi Kabir! I did some testing with this today. The extension worked fine at first (aside from a slight problem with dimension definition output), properly showing all master measures and dimensions, but I somehow broke it by adding tags to the measures.

Error behavior:
Started with app that had master measures and master dimensions defined. Extension functioned properly.
Added tag to a measure.
Measure list changed to "No results found."

Console error details:
`app.6.105.4.js:7 TypeError: Cannot read property 'forEach' of undefined
    at createTagList (master-items-viewer.js:72)
    at getMasterLibrary (master-items-viewer.js:34)
    at d.$scope.viewChange (master-items-viewer.js:40)
    at fn (eval at compile (app.6.105.4.js:7), <anonymous>:4:158)
    at i (app.6.105.4.js:7)
    at d.$eval (app.6.105.4.js:7)
    at d.$apply (app.6.105.4.js:7)
    at HTMLButtonElement.<anonymous> (app.6.105.4.js:7)
    at HTMLButtonElement.dispatch (app.6.105.4.js:7)
    at HTMLButtonElement.m.handle (app.6.105.4.js:7)`

Based on the stack trace error, it seems like something is leading to the `list` variable to be undefined when it tries to build the list of tags from the master measures in master-item-viewer.js:
`// create list of all tags with unique values
			var createTagList = function(list){
				var tagList=[];
				list.forEach(function(measure){
					if(measure.qData.tags.length > 0){
						measure.qData.tags.forEach(function(tag){
							if(!tagList.includes(tag)){
								tagList.push(tag);
							};
						});
					};
				});
				$scope.tags = tagList;`

Some troubleshooting steps taken:
- Refresh browser
- Hard refresh
- Clear browser cache

I go to a different app and can add the extension there, where it successfully displays the measures and dimensions. Even stranger, I tagged a measure and didn't experience the original bug. However, the first app is still bugged. I'm not sure what the difference is.

If you have any advice on testing steps or need more info, I'd love to help!

**Comment by kabir-rab** [comment]
That is odd - I will have to take a look, unfortunately I have limited access to the June version of Qlik Sense. I have deleted the VM with June 2019. I will see if i can find a backup of that VM and then I can retest this version of the extensions.

On the broken app - Have you tried removing the extensions, save and reload>reinsert the extension? I doubt this will fix anything but worth the try.

Thanks for the feedback.

**Comment by dagpunk** [comment]
@kabir-rab In the app where this happened, it automatically reloads nightly. I tried creating a new sheet today and adding the extension again, and it still shows an empty list.

**Comment by kabir-rab** [comment]
I suspect it the tags that is causing this, probably need to see the names of the tags. I will if we can get the list of all measures before initiated the tag list creation than I can look at this. I will add aversion with my debugging code in it, this will pipe the objects to console for you to look at.

**Comment by dagpunk** [comment]
@kabir-rab So far so good using version 1.0.0.2! All measures and dimensions are showing up. I'll be re-publishing the app within the next week or two, so I can provide an update after that if I run into more problems. Should I close this issue for now?

**Comment by dagpunk** [comment]
This latest version is running well, so I will now close this issue. Nice work!
