### ISSUE TITLE
Dimension output displays an object structure

### ISSUE THREAD

**Issue by dagpunk** [kabir-rab/master-items-viewer-lite#2]
On both calculated master dimensions and drill-down dimensions, it looks like the output is returning an object structure. Here's a sample of what is displayed in the dimensions' Expression/Formula column:
`{"qGrouping":"H","qFieldDefs":["Segment","Role","Name"],"qFieldLabels":[],"title":"Segment Role Employee Drill-Down","coloring":{...}}`

I see similar even for non-drill-down fields. It seems like only the content of qFieldDefs should be returned.

**Comment by kabir-rab** [comment]
![fix-dimension-def](https://user-images.githubusercontent.com/52291773/76864617-4d828980-6859-11ea-8001-8c3816669e73.png)

@viperior - This got overlooked when forking out at old commit. This is the correct way how I implemented this in the full version. This is working in June 2019 version. I will update the build shortly. 

Thanks
Kab

**Comment by dagpunk** [comment]
@kabir-rab Awesome! Thank you.
